### ISSUE TITLE
Multiple operators update all pomerium configs

### ISSUE THREAD

**Issue by lemaral** [pomerium/pomerium-operator#70]
I'm trying to use multiple pomerium instances (including the operator) to manage multiple subdomains, and I see that every instance is updating all the pomerium configs. It does not seems to be harmful, since rules that are not managed by the relevant instance of pomerium are ignored, but I would expect that only the operator's namespace pomerium config would be udated?

**Comment by travisgroth** [comment]
@lemaral could you elaborate on the setup a bit?  An instance of the operator only will only maintain a single secret and one set of deployments.  

Could they all be observing the same ingress resources?  By default, the operator monitors all namespaces.  You should be able to configure the operator to only monitor a single namespace with `--namespace`.  You could also use different ingress annotations and configure the operator accordingly with `--ingress-class`.

**Comment by travisgroth** [comment]
Closed by #143
