### ISSUE TITLE
Unclear documentation on annotation

### ISSUE THREAD

**Issue by karel-3d** [pomerium/pomerium-operator#75]
I am a bit unclear on the annotations.

The docs say:

> Following standard ingress controller behavior, pomerium-operator will respond only to resources that match the configured kubernetes.io/ingress.class and kubernetes.io/service.class annotations, or resources without any annotation at all.

but then the example below does not follow this? (it doesn't have the configured kubernetes.io/ingress.class; but also have annotations; so it shouldn't match?)

**Comment by travisgroth** [comment]
Ingress controllers will respond to their specific ingress class or ingress objects with no ingress annotation.  The operator follows the same behavior.  An ingress or service object with no class specification will always be evaluated by the operator for pomerium policy annotations.
