### ISSUE TITLE
Use Kubernetes as the direct source of truth for configuration without going through Kubernetes secrets

### ISSUE THREAD

**Issue by sim1** [pomerium/pomerium-operator#89]
Kubernetes secrets have a limit of 1MB.
This marks a hard limit for pomerium which makes pomerium-operator not viable for deployments at big scale, having to fall back to manage the file through the filesystem in other ways.

Ideally, pomerium should reach out directly to the Kubernetes API (through a ClusterRole which allows get access to ingresses), to be able to read the config for the ingress in question, the same way nginx-ingress does the same and then reconfigures itself.

**Comment by travisgroth** [comment]
FWIW I think - and correct me if I'm wrong - this impacts any pomerium deployment on kubernetes at the moment unless there's some additional custom work on top.  

For reference, how many routes did you have when you hit the limit?

**Comment by travisgroth** [comment]
Closed by #143 

This should be resolved by migrating to the [Pomerium Ingress Controller](https://github.com/pomerium/ingress-controller) ([docs](https://www.pomerium.com/docs/k8s/ingress.html)).  See [deprecation notice](https://github.com/pomerium/pomerium-operator#warning-deprecation-notice) for more info.
